version: "3.8"

services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    container_name: wakapi
    restart: unless-stopped
    volumes:
      - ./data:/wakapi/data
      - ./config.yml:/wakapi/config.yml
    ports:
      - "3000:3000"
    environment:
      - WAKAPI_CONFIG=/wakapi/config.yml
    command: sh -c "mkdir -p /wakapi/data && touch /wakapi/data/wakapi.db && chmod 666 /wakapi/data/wakapi.db && /app/entrypoint.sh"
    healthcheck:
      # use http because the wakapi service inside the container listens on http
      test: [CMD, wget, --spider, "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: wakapi-network
    driver: bridge
